config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root to: 'users#index'

  devise_for :users

  get '/users/sign_out', to: 'devise/sessions#destroy'

  get 'inbox', to: 'emails#inbox'
  get 'sent', to: 'emails#sent'
  get 'draft', to: 'emails#draft'
  get 'starred', to: 'emails#starred'
  get 'trash', to: 'emails#trash'

  resources :emails, only: [:show, :new, :create] do
    # Move all selected emails to `delete` folder
    put 'delete', to: 'emails#move_to_trash'

    # Unstar email items within the Starred category
    put 'unfavorite', to: 'emails#unfavorite'

    put 'starred', to: 'emails#mark_favorite'
    put 'unstarred', to: 'emails#mark_unfavorite'
    put 'read', to: 'emails#mark_read'
    put 'unread', to: 'emails#mark_unread'
  end

  put 'delete_selected_emails', to: 'emails#destroy'
end

app/views/layouts/shared/_interface.html.haml
-# haml-lint:disable LineLength
%h2= t('.mailbox')

.btn.btn-link{ type: 'button' }
  - if params[:locale] == User::ENGLISH_CODE
    = link_to t('.switch-language'), root_path(locale: User::CHINESE_CODE), class: 'link-color'
  - else
    = link_to t('.switch-language'), root_path(locale: User::ENGLISH_CODE), class: 'link-color'

.row
  .col-3.card.text-dark.bg-warning.mb-3.menu-opacity
    %h4.header.menu.text-primary.text-opacity-75= t('.menu')
    %ul.card-body
      = render 'layouts/shared/menu_side_bar'
  .col-9.card.text-dark-50.bg-info.mb-3.mail-opacity
    %h4.header.mail.text-primary.text-opacity-75= t('.mails')
    .card-body#emails

.btn.btn-link{ type: 'button' }
  = link_to t('.sign-out'), destroy_user_session_path, method: :delete, class: 'link-color' if user_signed_in?

app/views/layouts/shared/_menu_side_bar.html.haml
.row.compose
  %li
    %i.fas.fa-edit
    = link_to t('.compose'), new_email_path(locale: I18n.locale), remote: true, class: 'link-color'
.row
  %li
    %i.fas.fa-envelope
    = link_to t('.inbox'), inbox_path(locale: I18n.locale), remote: true
  %li
    %i.fas.fa-paper-plane
    = link_to t('.sent'), sent_path(locale: I18n.locale), remote: true, id: 'sent-button'
  %li
    %i.fas.fa-save
    = link_to t('.draft'), draft_path(locale: I18n.locale), remote: true
  %li
    %i.fas.fa-star
    = link_to t('.starred'), starred_path(locale: I18n.locale), remote: true
  %li
    %i.fas.fa-trash-alt
    = link_to t('.trash'), trash_path(locale: I18n.locale), remote: true